  
version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build:
    docker:
      - image: circleci/node:12.18.3

    steps:
      - checkout
      - run: npm install
      - run: npm test
      - slack/status:
          fail_only: false
          mentions: 'USERID1,USERID2'
          only_for_branches: only_for_branches
          webhook: webhook
